### ISSUE TITLE
Trainer + game crashes with new update to change number 24021053 on 06/18/2024

### ISSUE THREAD

**Issue by Prometheus2306** [jessy-lua/ALTF42_Trainer#1]
![altf42_crash](https://github.com/jessy-lua/ALTF42_Trainer/assets/18665645/b852da0d-99df-4e22-bafc-c4841a3d218e)

by the way, thank you for your time spent on this project. Being bad at this game is killing me ;)

**Comment by jessy-lua** [comment]
It looks like the game has been updated. I will check on it when I get home. Thank you for bringing this to my attention.

**Comment by jessy-lua** [comment]
The trainer has been fixed and can be downloaded from [this link](https://github.com/jessy-lua/ALTF42_Trainer/releases/latest). You can also compile it from the source yourself if you prefer. Thank you for your patience.
